### ISSUE TITLE
Order By support for getRelated

### ISSUE THREAD

**Issue by dig412** [shabbyrobe/amiss#14]
Related objects can be filtered by supplying a `Criteria` obects to the `getRelated` method, but `ORDER BY` clauses appear not to be supported.

The `runQuery` method in `Amiss\Sql\Relator\OneMany` assumes that if criteria are supplied then there are only `WHERE` conditions to satisfy.

Can this be fixed by adding support for the various kinds of criteria in the `runQuery` method?

**Comment by shabbyrobe** [comment]
I've introduced support for this in the new (as yet unreleased) version of Amiss (v5), but there are about a zillion BC breaks in it. The plan is to support v4 with bugfixes and as a PHP 5.3 compatible version, but v5 and beyond is where all new features will be added and has a PHP 5.6 minimum. I'll continue to support v4 with bugfixes if people are still using it and the new site will host both v4 and v5 documentation.

**Comment by dig412** [comment]
Excellent! I'm using `getList` as a work-around at the moment, but I'll definitely look at an upgrade when we move to 5.6.

**Comment by shabbyrobe** [comment]
Are there any other things you've been having trouble with or would like to see? I'm starting to polish v5 a bit now, but I might be able to sneak the odd new thing if it's not too radical.

**Comment by dig412** [comment]
I've just had a look through our version to see which features I've added over the past few months. Let me know if you'd like me to make pull requests for / elaborate on any of them!

* ~~Read only field support~~ (seems to be done in v5)
* Case-insensitive order by support (`ASC` vs `asc` etc.)
* `MetadataBuilder` class to provide a DSL for building metadata at runtime
* `CustomMapper` object to simplify writing classes to provide mapping for more complicated objects.
* `ChainMapper` to allow the use of multiple mappers at once - i.e. a stack that finds the top-most compatible mapper. I have Note at the bottom, and all our `CustomMappers` at the top.
* Extendable Criteria object for building DSLs to find particular entities.

MySQL Specific:
* Auto-generation of `ON DUPLICATE KEY UPDATE` clauses for `INSERT`s
* Support for `DELETE IGNORE`
* Handling for MySQL dropping the connection after inactivity (this was biting us in some long-running scripts)

**Comment by shabbyrobe** [comment]
Wow, this is great! I've added my own support for case insensitive ordering to v5 and pushed. Can you please send a pull request for the `ChainMapper`? That sounds awesome!

Would you mind if I opened separate issues for some of the other stuff? I'd really like to ask some follow-up questions about a few of the things you've added and separating the discussions by topic will make it a bit easier.

**Comment by dig412** [comment]
Sure thing, open one for ChainMapper as well, as I'm not completely happy with the implementation.

I won't be around a lot for the next couple of weeks as I'm getting married, but I'll try and get the code samples re-based onto v5 when I can.

**Comment by shabbyrobe** [comment]
That's awesome! Congratulations!

There's no hurry, I think I'll be hacking on v5 for a few weeks yet, particularly the documentation. Thanks heaps for your help and your thoughts.
