### ISSUE TITLE
CustomMapper object to simplify writing classes to provide mapping for more complicated objects.

### ISSUE THREAD

**Issue by shabbyrobe** [shabbyrobe/amiss#16]
Splitting discussion from #14 into separate discussions. Paging @dig412.

I haven't run into this need myself yet, can you please elaborate on the use case? I don't think I'm pushing Amiss as far as you have been so I'd be very interested to know how far you've been able to take it.

**Comment by dig412** [comment]
This one is primary for legacy compatibility - it lets me contain table-implementation-specific details in the Mapping layer without the entities or repositories needing to know about them.

Some of the tables I'm using Amiss to interface with are pretty grotty - they have columns that need particular values in to ensure compatibility with other software, or they have bit-field columns that I want to expose as multiple booleans, etc.

Generally I still want Amiss's column to field type-mapping functionality, so I didn't want to write a completely new mapper for each object and throw that away. `CustomMapper` provides hooks into the `Base` mapper so you can add additional logic before or after the object / row population process.

For example:
```php
public function populateObject($metadata, $event, $row)
{
	$fields = $metadata->getFields();
	$map    = $metadata->getColumnToPropertyMap();

	$event->isCancelled = ($row["event_status"] == "C");
	$event->isSoldOut   = ($row["event_status"] == "S");

	//Unset fields that we don't want to expose to the outside code
	$this->removeField($fields, $map, "status");

	$this->populateDefaultFields($fields, $map, $event, $row);
```

We also use a few fields that need special SQL handing - our primary keys are generated by a stored procedure for various replication-related reasons, but I *really* don't want that detail to leak out into the rest of the codebase, so when an object is saved with a `null` key the Mapper swaps it for `generate_unique_id()`. There are other columns that this is useful for - auto-incrementing version numbers, updated `created` or `updated` timestamps when MySQL will only handle one of them, etc.

In an ideal world I would change the table structure to not require much of this functionality, but I've found this to be incredibly useful in dealing with any kind of strange setup that the Note / Array mapper can't deal with.

Although it's probably a very specific use case I think the `Base` mapper could probably be changed to allow these hooks without a lot of impact on the rest of the code.

**Comment by shabbyrobe** [comment]
> Although it's probably a very specific use case I think the Base mapper could probably be changed to allow these hooks without a lot of impact on the rest of the code.

Definitely. Good idea. v5 already has support for events in `Amiss\Sql\Manager`, so there's an idiom there already to work with. I already have `(before|after)(Insert|Update|Delete)` in the Manager. Is there somewhere in the Manager we can hook to do what you want or is it only possible in the mapper? If the latter, where do you reckon is the best spot to hook?
