### ISSUE TITLE
ChainMapper to allow the use of multiple mappers at once

### ISSUE THREAD

**Issue by shabbyrobe** [shabbyrobe/amiss#17]
Splitting discussion from #14 into separate discussions. Paging @dig412.

> ChainMapper to allow the use of multiple mappers at once - i.e. a stack that finds the top-most compatible mapper. I have Note at the bottom, and all our CustomMappers at the top.

Definitely want to see this one in there for v5, I have already got a place in my own code where it would be a benefit.

**Comment by dig412** [comment]
This one is linked to #16  - I have a bunch of CustomMappers I want to use for one class each, and then Note for everything else.

I set up the mappers as so:

```php
$chain                  = new Mapper\Chain();
$chain->objectNamespace = "Ents24\Entity";

//Handlers are added in order of most specific to least specific
$chain->addMapper(new Mapper\Event());
$chain->addMapper(new Mapper\Artist());
$chain->addMapper(new Mapper\Venue());
$chain->addMapper(new Mapper\Announcement());
$chain->addMapper(new Mapper\Content());
$chain->addMapper(new Amiss\Mapper\Note());

$manager = Amiss::createSqlManager($connector, $chain);
```

then `ChainMapper` intercepts the `fromObject` and `toObject` calls, iterates over the registered mappers calling `$mapper->supportsClass($className)` on each one until it finds a match, then hands off the method call.

It's pretty simple, but the `supportsClass()` method is where the design is required, as at the moment Note just does `return true` as I always have it at the bottom of the stack.

An alternative could be that a Mapper should report the classes it can handle to ChainMapper when it is registered, so they can be cached. This would cause problems for autoloader-driven mappers like Note though.

**Comment by shabbyrobe** [comment]
> An alternative could be that a Mapper should report the classes it can handle to ChainMapper when it is registered, so they can be cached. This would cause problems for autoloader-driven mappers like Note though.
Could have it both ways? The mapper could report the list of classes if it knows them, or `false` if it doesn't. Keep a list of all mappers that report `false`, then if the class-to-mapper entry isn't found in the cache, iterate through the falsey ones calling getMeta() until you get an answer. That answer can also be cached into an `Amiss\Cache` if one is provided. This is just an 'off the top of the head' idea, so I could be missing a crapload of pertinent details.

**Comment by shabbyrobe** [comment]
I've pushed an implementation of this to the v5 development branch. Took your advice about the `supportsClass` rather than the v4-specific hacks I suggested, but that took some cleanup work to work with the Note mapper. I agree that you'll more than likely have it last in the stack, but I didn't want someone to find out the hard way that you can't do that so the Note mapper supports it too.

The problem I ran into was `determineTypeHandler`. It's the only method on the mapper that doesn't take meta as an argument, and contains no information that can be used to select a child mapper. What's the best way to deal with this? Should the Chain mapper inherit `Amiss\Mapper\Base` and handle types itself, or should it delegate to the mappers? Or both?

**Comment by shabbyrobe** [comment]
v5 is now master, this is available in the latest release.
