### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by shabbyrobe** [shabbyrobe/amiss#21]
Splitting discussion from #14 into separate discussions. Paging @dig412.

> MySQL dropping the connection after inactivity [...] was biting us in some long-running scripts

This old chestnut! Love to see what you have here, I dread this error.

I've factored out the Connector component into shabbyrobe/pdok. Does this issue belong in that project?

**Comment by dig412** [comment]
Yep, part of the fix lives in Connector, in the query method:

```php
const MYSQL_SERVER_GONE_ERROR = 2006;
//..snip...
try {
    return call_user_func_array(array($pdo, 'query'), $args);
} catch (\PDOException $e) {
    $mysqlErrorCode = isset($e->errorInfo[1]) ? (int) $e->errorInfo[1] : null;

    switch ($mysqlErrorCode) {
        case self::MYSQL_SERVER_GONE_ERROR:
            //Catch "server has gone away" error, reconnect and retry.
            //Even though the error mode is set to "Exception", pdo will log an error
            //See https://bugs.php.net/bug.php?id=63812
            $this->disconnect();
            $this->connect();
            return call_user_func_array(array($this, 'query'), $args);
            break;

        default:
            throw $e;
            break;
    }
}
```

This works for one-off queries, but the SQL\Manager class uses PDOStatements, which appear to have their own internal pointer to the connection that you can't override or replace, so I've had to duplicate the fix in the `execute` method of Manager:

```php
try {
    $stmt->execute($params);
} catch (\PDOException $e) {

    $mysqlErrorCode = isset($e->errorInfo[1]) ? (int) $e->errorInfo[1] : null;

    switch ($mysqlErrorCode) {
        case Connector::MYSQL_SERVER_GONE_ERROR:
            //Catch "server has gone away" error, reconnect and retry.
            //Even though the error mode is set to "Exception", pdo will log an error
            //See https://bugs.php.net/bug.php?id=63812
            $con = $this->getConnector();
            $con->disconnect();
            $con->connect();
            //The PDOStatement contains a hidden pointer to the current connection, so we have to re-build it
            //to ensure the pointer is valid.
            $stmt = $con->prepare($stmt->queryString);
            $stmt->execute($params);
            break;

        default:
            throw $e;
            break;
    }
}
```

It would be really good to be able to centralise the logic for that fix, at least all in the Connector.

**Comment by shabbyrobe** [comment]
In Amiss v5, I have moved the Connector class out into a separate library: http://github.com/shabbyrobe/pdok. PDOK actually uses its own PDOStatement object by default - this means we can probably do exactly what you suggest and centralise the logic.

I'm going to close this issue here and re-open it in the PDOK issues. I probably should've opened it there in the first place! Oops :)
